export const icons = {
  menu1korean: require("../../../public/assets/icon/menu-1-korean.png"),
  menu2chinese: require("../../../public/assets/icon/menu-2-chinese.png"),
  menu3japanese: require("../../../public/assets/icon/menu-3-japanese.png"),
  menu4wastern: require("../../../public/assets/icon/menu-4-wastern.png"),
  menu5snack: require("../../../public/assets/icon/menu-5-snack.png"),
  menu6asian: require("../../../public/assets/icon/menu-6-asian.png"),
  menu7soup: require("../../../public/assets/icon/menu-7-soup.png"),
  menu8fastfood: require("../../../public/assets/icon/menu-8-fastfood.png"),
  menu9brunch: require("../../../public/assets/icon/menu-9-brunch.png"),
  menu10salad: require("../../../public/assets/icon/menu-10-salad.png"),
  menu11chicken: require("../../../public/assets/icon/menu-11-chicken.png"),
  menu12pizza: require("../../../public/assets/icon/menu-12-pizza.png"),
  menu13cafe: require("../../../public/assets/icon/menu-13-cafe.png"),
  menu14bar: require("../../../public/assets/icon/menu-14-bar.png"),
  menu15etc: require("../../../public/assets/icon/menu-15-etc.png"),
  banner: require("../../../public/assets/icon/banner-img.png"),
  rest1: require("../../../public/assets/icon/rest-1-image.png"),
  rest2: require("../../../public/assets/icon/rest-2-image.png"),
  rest3: require("../../../public/assets/icon/rest-3-image.png"),
  rest4: require("../../../public/assets/icon/rest-4-image.png"),
  rest5: require("../../../public/assets/icon/rest-5-image.png"),
  help: require("../../../public/assets/icon/help-icon.svg"),
  logo: require("../../../public/assets/icon/logo-icon.svg"),
  person: require("../../../public/assets/icon/person-icon.svg"),
  search: require("../../../public/assets/icon/search-icon.svg"),
} as const;
